cobl/extensional_semantics/urls.py
from django.conf.urls import url, patterns
from cobl.extensional_semantics.views import add_lexeme_extension_citation, \
                                              add_relation, \
                                              add_semantic_domain, \
                                              delete_semantic_domain, \
                                              domains_list, \
                                              edit_relation, \
                                              edit_semantic_domain, \
                                              extension_citation_view, \
                                              language_domains_list, \
                                              language_domain_view, \
                                              lexeme_domains_list, \
                                              lexeme_domain_view, \
                                              lexeme_extensions_view, \
                                              view_relation, \
                                              view_semantic_domain
from cobl.urls import R

# TODO move these views to:
# from cobl.extensional_semantics.views import *

urlpatterns = patterns(
    '',
    # Semantic relations
    url(r'^relation/add/$', add_relation, name="add-relation"),
    url(r'^relation/%(RELATION)s/edit/$' % R, edit_relation,
        name="edit-relation"),
    url(r'^relation/%(RELATION)s/$' % R, view_relation,
        name="view-relation"),

    # Semantic domains (lists of semantic relations)
    url(r'^domains/$', domains_list, name="view-domains"),
    url(r'^domains/add-new/$', add_semantic_domain,
        name="add-semantic-domain"),
    url(r'^domain/%(DOMAIN)s/$' % R, view_semantic_domain,
        name="view-semantic-domain"),
    url(r'^domain/%(DOMAIN)s/edit/$' % R, edit_semantic_domain,
        name="edit-semantic-domain"),
    url(r'^domain/%(DOMAIN)s/delete/$' % R, delete_semantic_domain,
        name="delete-semantic-domain"),

    url(r'^language/%(LANGUAGE)s/domain/%(DOMAIN)s/$' % R,
        language_domain_view, name="language-domain-view"),
    url(r'^language/%(LANGUAGE)s/domains/$' % R,
        language_domains_list, name="language-domains-list"),

    # Semantic extensions of lexemes -- within a specified domain
    url(r'^lexeme/%(LEXEME_ID)s/domains/$' % R,
        lexeme_domains_list, name="lexeme-domains-list"),
    url(r'^lexeme/%(LEXEME_ID)s/domain/%(DOMAIN)s/$' % R,
        lexeme_domain_view, name="lexeme-domain-view"),
    url(r'^lexeme/%(LEXEME_ID)s/extensions/$' % R,
        lexeme_extensions_view, name="lexeme-extensions-view"),
    # TODO isn't working yet
    url(r'^lexeme/%(LEXEME_ID)s/domain/%(DOMAIN)s/edit/$' % R,
        lexeme_domain_view, {"action": "edit"},
        name="edit-lexeme-extensions"),

    # Semantic extensions of lexemes -- individual extensions
    url((r'^domain/%(DOMAIN)s/extension/'
         '(?P<extension_id>\d+)/add-citation/$') % R,
        add_lexeme_extension_citation, name="add-domain-extension-citation"),
    url(r'^extension/(?P<extension_id>\d+)/add-citation/$',
        add_lexeme_extension_citation, name="extension-add-citation"),
    # url(r'^extension/(?P<extension_id>\d+)/$',
    #         view_lexeme_extension_citation, name="view-extension"),


    # citation/object/id patterns
    url(r'^citation/extension/(?P<citation_id>\d+)/$',
        extension_citation_view, name="citation-extension-view"),
    )

cobl/urls.py
import debug_toolbar
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import login, logout
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import DetailView, \
        ListView, RedirectView
from django.views.static import serve as serveStatic
from cobl.views import add_language_list, \
                        add_meaning_list, \
                        changeDefaults, \
                        cognate_report, \
                        delete_language, \
                        delete_language_list, \
                        delete_meaning, \
                        edit_language, \
                        edit_language_list, \
                        edit_meaning_list, \
                        edit_meaning, \
                        edit_wordlist, \
                        overview_language, \
                        language_add_new, \
                        lexeme_add, \
                        lexeme_duplicate, \
                        lexeme_edit, \
                        lexeme_search, \
                        meaning_add_new, \
                        redirect_lexeme_citation, \
                        reorder_language_list, \
                        reorder_meaning_list, \
                        reorder_wordlist, \
                        revert_version, \
                        source_edit, \
                        source_list, \
                        source_view, \
                        source_import, \
                        source_cognacy, \
                        source_cogset, \
                        source_lexeme, \
                        SourceAutocomplete, \
                        export_bibtex, \
                        viewAbout, \
                        viewAuthors, \
                        viewAuthor, \
                        view_changes, \
                        view_clades, \
                        view_cognateclasses, \
                        view_all_cognateclasses, \
                        viewDefaultCognateClassList, \
                        viewDefaultLanguage, \
                        viewDefaultMeaning, \
                        view_frontpage, \
                        view_language_check, \
                        view_language_list, \
                        view_language_wordlist, \
                        view_lexeme, \
                        view_meaning, \
                        view_object_history, \
                        view_sndComp, \
                        view_wordlist, \
                        view_wordlists, \
                        view_nexus_export, \
                        view_two_languages_wordlist, \
                        view_language_progress, \
                        view_language_distributions, \
                        json_cognateClass_placeholders, \
                        view_cladecognatesearch, \
                        view_csvExport, \
                        ping, \
                        _raise, \
                        viewProblematicRomanised
from cobl.viewCsvImport import viewCsvImport
from cobl import settings
from cobl.lexicon.views import CognateClassCitationCreateView, \
                                cognate_class_citation_delete, \
                                CognateClassCitationUpdateView, \
                                DumpRawDataView, \
                                NexusExportView
from cobl.lexicon.models import CognateClassCitation, \
                                 CognateJudgement, \
                                 CognateJudgementCitation, \
                                 LanguageList, \
                                 LexemeCitation, \
                                 MeaningList
from cobl.profiles.views import view_profile, alter_profile, change_password

admin.autodiscover()

# standard regexes for urls
# url_char = "a-zA-Z0-9$_.+!*'(),-" # unreserved
url_char = "A-Za-z0-9_.~-"  # unreserved
# http://tools.ietf.org/html/rfc3986#section-2.3
R = {
    "COGJUDGE_ID": r"(?P<cogjudge_id>\d+)",
    "COGNATE_NAME": r"(?P<cognate_name>[{0}]+)".format(url_char),
    "DOMAIN": r"(?P<domain>[{0}]+)".format(url_char),
    "LANGUAGE": r"(?P<language>[{0}]+)".format(url_char),
    "LANGUAGELIST": r"(?P<language_list>[{0}]+)".format(url_char),
    "MEANINGLIST": r"(?P<meaning_list>[{0}]+)".format(url_char),
    "LEXEME_ID": r"(?P<lexeme_id>\d+)",
    "LEXEME_IDS": r"(?P<lexeme_id>[0-9,]+)",
    "MEANING_ID": r"(?P<meaning_id>\d+)",
    "MEANING": r"(?P<meaning>[{0}]+)".format(url_char),
    "RELATION": r"(?P<relation>[{0}]+)".format(url_char),
    "WORDLIST": r"(?P<wordlist>[{0}]+)".format(url_char),
    "USERNAME": r"(?P<username>[a-zA-Z0-9@.+_-]+)",
    "ROOTREFLANG": r"(?P<root_ref_lang>.+)",
    "identifier": r"[a-zA-Z_][a-zA-Z0-9_]*",
    }

urlpatterns = [
    # Front Page
    url(r'^$', view_frontpage, name="view-frontpage"),
    url(r'^changes/$', view_changes, name="view-changes"),
    url(r'^changes/%(USERNAME)s/$' % R, view_changes,
        name="view-changes-user"),

    # csv Exports
    url(r'^csvExport/$', view_csvExport, name="view-csvExport"),

    # Language list
    url(r'^languages/$', view_language_list),
    url(r'^languagelist/add-new/$', add_language_list,
        name="add-language-list"),
    url(r'^languagelist/%(LANGUAGELIST)s/$' % R, view_language_list,
        name="view-language-list"),
    url(r'^languagelist/%s/$' % LanguageList.DEFAULT, view_language_list,
        name="view-all-languages"),
    url(r'^languagelist/%(LANGUAGELIST)s/edit/$' % R, edit_language_list,
        name="edit-language-list"),
    url(r'^languagelist/%(LANGUAGELIST)s/reorder/$' % R, reorder_language_list,
        name="reorder-language-list"),
    url(r'^languagelist/%(LANGUAGELIST)s/delete/$' % R, delete_language_list,
        name="delete-language-list"),
    url(r'^languagelist/$',  # view all language lists
        ListView.as_view(
            queryset=LanguageList.objects.all(),
            context_object_name="language_lists"),
        name="view-language-lists"),

    # Language progress (#311):
    url(r'^languageprogress/%(LANGUAGELIST)s/(onlyexport|onlynotexport)?$' % R, view_language_progress,
        name="view-language-progress"),

    # Language distributions:
    url(r'^languagedistributions/%(LANGUAGELIST)s/$' % R,
        view_language_distributions,
        name="view-language-distributions"),

    # Language check (#159):
    url(r'^language/check$' % R, view_language_check),
    url(r'^language/%(LANGUAGE)s/check$' % R, view_language_check,
        {"wordlist": MeaningList.DEFAULT}),
    url(r'^language/%(LANGUAGE)s/wordlist/%(WORDLIST)s/check$' % R,
        view_language_check),

    # Language
    url(r'^language/$' % R, viewDefaultLanguage),
    url(r'^language/%(LANGUAGE)s/$' % R, view_language_wordlist,
        {"wordlist": MeaningList.DEFAULT}, name="language-report"),
    url(r'^language/%(LANGUAGE)s/wordlist/%(WORDLIST)s/$' % R,
        view_language_wordlist, name="view-language-wordlist"),
    url(r'^language/%(LANGUAGE)s/edit/$' % R, edit_language,
        name="language-edit"),
    url(r'^language/%(LANGUAGE)s/overview/$' % R, overview_language,
        name="language-overview"),
    url(r'^language/%(LANGUAGE)s/delete/$' % R, delete_language,
        name="language-delete"),
    url(r'^language/%(LANGUAGE)s/add-lexeme/' % R,
        lexeme_add, name="language-add-lexeme"),
    url(r'^language/%(LANGUAGE)s/meaning/%(MEANING)s/add-lexeme/' % R,
        lexeme_add, name="language-meaning-add-lexeme"),
    url(r'^languagelist/%(LANGUAGELIST)s/add-new/$' % R, language_add_new,
        name="language-add-new"),

    # Clades:
    url(r'^clades/$' % R, view_clades),
    # SndComp sets:
    url(r'^sndComp/$' % R, view_sndComp),
    # Clade cognate search:
    url(r'^cladecognatesearch/$' % R, view_cladecognatesearch),

    # Meanings (aka wordlist)
    url(r'^meaninglist/add-new/$', add_meaning_list,
        name="add-meaning-list"),
    url(r'^meaninglist/edit/$', edit_meaning_list,
        name="edit-meaning-list"),
    url(r'^meaninglist/%(MEANINGLIST)s/edit/$' % R, edit_meaning_list,
        name="edit-meaning-list"),
    url(r'^meaninglist/%(MEANINGLIST)s/reorder/$' % R, reorder_meaning_list,
        name="reorder-meaning-list"),

    url(r'^wordlists/$', view_wordlists, name="view-wordlists"),
    url(r'^wordlist/%(WORDLIST)s/$' % R, view_wordlist, name="view-wordlist"),
    url(r'^wordlist/%(WORDLIST)s/edit/$' % R, edit_wordlist,
        name="edit-wordlist"),
    url(r'^wordlist/%(WORDLIST)s/reorder/$' % R, reorder_wordlist,
        name="reorder-wordlist"),
    url(r'^meanings/$', view_wordlist,
        {"wordlist": MeaningList.DEFAULT}, name="view-meanings"),
    url(r'^meanings/add-new/$', meaning_add_new, name="meaning-add-new"),
    url(r'^meaning/%(MEANING)s/edit/$' % R, edit_meaning,
        name="edit-meaning"),

    # Meaning
    url(r'^meaning/%(MEANING)s/add-lexeme/$' % R, lexeme_add,
        name="meaning-add-lexeme"),
    url(r'^meaning/%(MEANING)s/languagelist/%(LANGUAGELIST)s/$' % R,
        view_meaning,
        name="view-meaning-languages"),
    url(r'^meaning/%(MEANING)s/languagelist/'
        '%(LANGUAGELIST)s/add-cognate/%(LEXEME_ID)s/$' % R,
        view_meaning, name="view-meaning-languages-add-cognate"),
    url(r'^meaning/%(MEANING)s/$' % R, view_meaning, {"language_list": None},
        name="meaning-report"),
    url(r'^meaning/%(MEANING)s/delete/$' % R, delete_meaning,
        name="delete-meaning"),
    url(r'^meaning/%(MEANING)s/language/%(LANGUAGE)s/add-lexeme/' % R,
        lexeme_add, name="meaning-language-add-lexeme"),
    url(r'^meaning/$' % R, viewDefaultMeaning),

    # Lexemes
    url(r'^lexeme/add/', lexeme_add),
    url(r'^lexeme/search/$', lexeme_search, name="lexeme-search"),

    url(r'^lexeme/%(LEXEME_ID)s/duplicate/$' % R, lexeme_duplicate),

cobl/extensional_semantics/models.py
from django.db import models
from django.core.validators import validate_comma_separated_integer_list
import reversion
from cobl.lexicon.models import AbstractBaseCitation


# @reversion.register
class SemanticRelation(models.Model):
    relation_code = models.CharField(max_length=64)
    long_name = models.CharField(max_length=128)
    description = models.TextField(blank=True)
    notes = models.TextField(blank=True)
    modified = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return "/relation/%s/" % self.relation_code

    def __str__(self):
        return str("%s (%s)" % (self.relation_code, self.long_name))


# @reversion.register
class SemanticExtension(models.Model):
    lexeme = models.ForeignKey('lexicon.Lexeme')
    relation = models.ForeignKey(SemanticRelation)
    source = models.ManyToManyField(
        'lexicon.Source', through="SemanticExtensionCitation")
    modified = models.DateTimeField(auto_now=True)

    def reliability_ratings(self):
        return set(
            self.semanticextensioncitation.values_list(
                "reliability", flat=True))

    def get_absolute_url(self):
        return "/extension/%s/" % self.id

    def __str__(self):
        return u"%s" % (self.id)


# @reversion.register
class SemanticExtensionCitation(AbstractBaseCitation):
    extension = models.ForeignKey(SemanticExtension)
    source = models.ForeignKey('lexicon.Source')

    def get_absolute_url(self):
        return "/citation/extension/%s/" % self.id

    def __str__(self):
        return u"<SEC %s src=%s sec=%s>" % \
            (self.id, self.extension.id, self.source.id)

    class Meta:
        unique_together = (("extension", "source"),)


# @reversion.register
class SemanticDomain(models.Model):
    """A named, ordered list of semantic relations (referred to as a 'domain'
    in the user interface) for use in display and output. A default list, named
    'all' is (re)created on save/delete of the Language table (cf.
    cobl.models.update_semantic_domain_all)"""
    DEFAULT = "all"

    name = models.CharField(max_length=999, unique=True)
    description = models.TextField(blank=True, null=True)
    relation_ids = models.CharField(
        blank=True,
        max_length=999,
        validators=[validate_comma_separated_integer_list])
    modified = models.DateTimeField(auto_now=True)

    def _get_list(self):
        try:
            return [int(i) for i in self.relation_ids.split(",")]
        except ValueError:
            return []

    def _set_list(self, listobj):
        self.relation_ids = ",".join([str(i) for i in listobj])

    relation_id_list = property(_get_list, _set_list)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]


def update_semantic_domain_all(sender, instance, **kwargs):
    try:
        sd = SemanticDomain.objects.get(name=SemanticDomain.DEFAULT)
    except:
        desc = "Default semantic domain containing a " \
               "list of all semantic relations"
        sd = SemanticDomain.objects.create(
            name=SemanticDomain.DEFAULT, description=desc)
    compareList = list(SemanticRelation.objects.values_list("id", flat=True))
    if sd.relation_id_list != compareList:
        sd.relation_id_list = [l.id for l in SemanticRelation.objects.all()]
        sd.save(force_update=True)


models.signals.post_save.connect(
    update_semantic_domain_all, sender=SemanticRelation)
models.signals.post_delete.connect(
    update_semantic_domain_all, sender=SemanticRelation)

# for modelclass in [SemanticRelation,
#         SemanticExtension,
#         SemanticExtensionCitation,
#         SemanticDomain]:
#     if not reversion.is_registered(modelclass):
#         reversion.register(modelclass)

cobl/profiles/models.py
# Create your models here.

cobl/website/models.py
# empty file to signal to django to treat this directory as an app

cobl/profiles/forms.py
from django.contrib.auth.models import User
from django import forms
# http://docs.djangoproject.com/en/dev/topics/auth/#module-django.contrib.auth.forms
# from django.contrib.auth.forms import


class UserAlterDetailsForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ["first_name", "last_name", "email", "is_active"]

# class UserAlterPasswordForm(forms.ModelForm):
#
#     class Meta:
#         model = User
#         fields = ["password"]

cobl/templates/about.html
{% extends "base.html" %}

{% load staticfiles %}
{% load wtforms %}

{% block title %}
  {{ title }}
{% endblock %}

{% block controls %}
  {% include "snippets/defaultSelections.html" %}
  {% include "snippets/go_to.html" %}
{% endblock %}

{% block top %}
{% endblock %}

{% block content %}
  <div class="row">
    {# Because of markdown make sure no spaces are added to content! #}
    <div class="col-md-12 well markdown">{{ content }}</div>
  </div>
{% endblock %}
{# vim: set ft=htmldjango nowrap shiftwidth=2 expandtab: #}

cobl/templates/author.html
{% extends "base.html"%}

{% load staticfiles %}
{% load wtforms %}

{% block title %}
  Author: {{ author.fullName }}
{% endblock %}

{% block top %}
{% endblock %}

{% block controls %}
  {% include "snippets/defaultSelections.html" %}
  {% include "snippets/go_to.html" %}
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-3">
      <table class="table">
        <tbody>
          <tr>
            <th colspan="2">
              {% if author.getAvatar %}
              <img src="{{ author.getAvatar }}" class="thumbnail"/>
              {% endif %}
              <h1>{{ author.fullName }}</h1>
            </th>
          </tr>
          {% if author.website %}
          <tr>
            <th>Website</th>
            <td>
              <a href="{{ author.website }}" target="_blank">{{ author.website }}</a>
            </td>
          </tr>
          {% endif %}
          {% if author.email %}
          <tr>
            <th>Email</th>
            <td>{{ author.displayEmail }}</td>
          </tr>
          {% endif %}
          {% if authored %}
          <tr>
            <th>Author of</th>
            <td>
              <ul>
                {% for a, u in authored %}
                <li>
                  <a href="{% url 'view-language-wordlist' a wordlist %}">{{ u }}</a>
                </li>
                {% endfor %}
              </ul>
            </td>
          </tr>
          {% endif %}
          {% if reviewed %}
          <tr>
            <th>Reviewer of</th>
            <td>
              <ul>
                {% for a, u in reviewed %}
                <li>
                  <a href="{% url 'view-language-wordlist' a wordlist %}">{{ u }}</a>
                </li>
                {% endfor %}
              </ul>
            </td>
          </tr>
          {% endif %}
        </tbody>
      </table>
    </div>
    <div class="col-md-9 markdown">
      {{ content }}
    </div>
  </div>
{% endblock %}
{# vim: set ft=htmldjango nowrap shiftwidth=2 expandtab: #}

cobl/templates/edit_wordlist.html
{% extends "base.html" %}

{% block title %}{{ wordlist.name }}{% endblock %}

{% block top %}
  <h1>{{ wordlist.name }}</h1>
{% endblock %}

{% block content %}
  Leave fields blank for no change (i.e. keeping the [value])
  <form action="" method="POST">{% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" name="submit" value="Submit">
    <input type="submit" name="cancel" value="Cancel">
  </form>
{% endblock %}

{% block controls %}
  {% include "snippets/defaultSelections.html" %}
  {% include "snippets/go_to.html" %}
{% endblock %}
{# vim: set ft=htmldjango nowrap shiftwidth=2 expandtab: #}

cobl/templates/language_check.html
<table class="table table-condensed">
  <thead>
    <tr>
      <th colspan="2">
        Meanings
      </th>
    </tr>
  </thead>
  <tbody>
    {% for mCount in meaningCounts %}
      <tr>
        <td>
          {{ mCount.count }}
        </td>
        <td>
          {{ mCount.meaning }}
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>
{# vim: set ft=htmldjango nowrap shiftwidth=2 expandtab: #}

cobl/templates/lexeme_add.html
{% extends "base.html" %}

{% load wtforms %}

{% block title %}Add lexeme{% endblock %}

{% block top %}
  <h1>Add lexeme</h1>
{% endblock %}

{% block content %}
  <form action="" method="POST" class="form-horizontal">
    {% csrf_token %}
    <div class="form-group">
      <label for="typeaheadLanguageId" class="col-sm-2 control-label">
        {{ form.language_id.label }}
      </label>
      <div class="col-sm-3">
        <input id="typeaheadLanguageId"
               type="text"
               class="typeaheadInput form-control"
               data-inputfor="language_id"
               data-typeahead="{{ languageTypeahead | escapejs }}"
               value="">
      </div>
      <label for="language_id" class="col-sm-2" control-label>
        Language ID:
      </label>
      <div class="col-sm-2">
        {% form_field form.language_id pattern="\d+" class="form-control" required="required" placeholder="Filled in by Language" %}
      </div>
    </div>
    <div class="form-group">
      <label for="typeaheadMeaningId" class="col-sm-2 control-label">
        {{ form.meaning_id.label }}
      </label>
      <div class="col-sm-3">
        <input id="typeaheadMeaningId"
               type="text"
               class="typeaheadInput form-control"
               data-inputfor="meaning_id"
               data-typeahead="{{ meaningTypeahead | escapejs }}"
               value="">
      </div>
      <label for="meaning_id" class="col-sm-2" control-label>
        Meaning ID:
      </label>
      <div class="col-sm-2">
        {% form_field form.meaning_id pattern="\d+" class="form-control" required="required" placeholder="Filled in by Meaning" %}
      </div>
    </div>
    <div class="form-group">
      <label for="romanised" class="col-sm-2 control-label">
        {{ form.romanised.label }}
      </label>
      <div class="col-sm-3">
        {% form_field form.romanised class="form-control" %}
      </div>
    </div>
    <div class="form-group">
      <label for="nativeScript" class="col-sm-2 control-label">
        {{ form.nativeScript.label }}
      </label>
      <div class="col-sm-3">
        {% form_field form.nativeScript class="form-control" %}
      </div>
    </div>
    <div class="form-group">
      <label for="phon_form" class="col-sm-2 control-label">
        {{ form.phon_form.label }}
      </label>
      <div class="col-sm-3">
        {% form_field form.phon_form class="form-control" %}
      </div>
    </div>
    <div class="form-group">
      <label for="phoneMic" class="col-sm-2 control-label">
        {{ form.phoneMic.label }}
      </label>
      <div class="col-sm-3">
        {% form_field form.phoneMic class="form-control" %}
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-3">
        <a href="." class="btn btn-default">Cancel</a>
        <input class="btn btn-danger" type="submit" name="submit" value="Create">
      </div>
    </div>
  </form>
{% endblock %}

{% block controls %}
  {% include "snippets/defaultSelections.html" %}
  {% include "snippets/go_to.html" %}
{% endblock %}
{# vim: set ft=htmldjango nowrap shiftwidth=2 expandtab: #}

cobl/templates/lexeme_extensions_edit.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}Semantic extensions{% endblock %}

{% block top %}
<h1>
  Semantic extensions: {{ lexeme }} ({{ lexeme.language.utf8_name }})
</h1>
{% endblock %}

{% block content %}
  <table>
    <tr>
      <th>Code</th>
      <th>Relation</th>
      <th>Description</th>
      <th>Citations</th>
    </tr>
    {% for extension in lexeme.semanticextension_set.all %}
      <tr class="{% cycle 'odd' 'even' %}">
        <td>{{ extension.relation.relation_code }}</td>
        <td>{{ extension.relation.long_name }}</td>
        <td>{{ extension.relation.description }}</td>
        <td>
          {% for citation in semantic_extension.semanticextensioncitation_set.all %}
            <a href="{{ citation.get_absolute_url }}" alt="{{ citation.source.shorthand }}">
              [{{ citation.source.id }}]
            </a>
          {% endfor %}
          {# TODO #}
          {#<a href="{% url 'add-domain-extension-citation' domain semantic_extension.id %}"> #}
          {#   <img src="{% static 'buttons/add.png' %}" alt="Add citation" title="Add citation"> #}
          {#</a> #}
        </td>
      </tr>
    {% endfor %}
  </table>
{% endblock %}

{% block controls %}
  {% include "snippets/defaultSelections.html" %}
  {% include "snippets/go_to.html" %}
  {% if action != "edit" %}
    <li>
      <a href="{% url 'edit-lexeme-extensions' lexeme.id domain %}">Edit semantic extensions</a>
    </li>
  {% endif %}
    <li>
      <a href="{% url 'view-lexeme' lexeme.id %}">Back to lexeme ‘{{ lexeme }}’</a>
    </li>
  {% if lexeme.meaning %}
    <li>
      <a href="{% url 'meaning-report' lexeme.meaning.gloss %}">
        Back to meaning list ‘{{ lexeme.meaning.gloss }}’
      </a>
    </li>
  {% endif %}
  <li>
    <a href="{% url 'language-report' lexeme.language.ascii_name %}">
      Back to language list ‘{{ lexeme.language.utf8_name }}’
    </a>
  </li>
{% endblock %}
{# vim: set ft=htmldjango nowrap shiftwidth=2 expandtab: #}

cobl/templates/lexeme_search.html
{% extends "base.html" %}

{% block title %}
  Search lexeme
{% endblock %}

{% block top %}
  <h1>
    Search {{ language.utf8_name }}
  </h1>
{% endblock %}

{% block controls %}
  {% include "snippets/defaultSelections.html" %}
  {% include "snippets/go_to.html" %}
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-4">
      <form action="" method="POST">
        {% csrf_token %}
        <table class="table">
          {{ form.as_table }}
        </table>
        <input type="submit" name="submit" value="Submit" class="btn btn-primary">
      </form>
    </div>
  </div>
{% endblock %}
{# vim: set ft=htmldjango nowrap shiftwidth=2 expandtab: #}

cobl/templates/relation_edit.html
{% extends "base.html" %}

{% block title %}{{ relation }}{% endblock %}

{% block top %}
  <h1>{{ relation }}</h1>
{% endblock %}

{% block content %}
  <form action="" method="POST">{% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" name="submit" value="Submit">
    <input type="submit" name="cancel" value="Cancel">
  </form>
{% endblock %}

{% block controls %}
  {% include "snippets/defaultSelections.html" %}
  {% include "snippets/go_to.html" %}
{% endblock %}
{# vim: set ft=htmldjango nowrap shiftwidth=2 expandtab: #}